// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjiRy65mrit_KUuKD9n4HY_wgdHeTL2G4',
    appId: '1:872296974646:web:6b68f75ee1031cbcbd0b97',
    messagingSenderId: '872296974646',
    projectId: 'siproject-c5cd0',
    authDomain: 'siproject-c5cd0.firebaseapp.com',
    storageBucket: 'siproject-c5cd0.appspot.com',
    measurementId: 'G-KXS4S0VGGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADyipDo7A7pY219eQkMJ5_pCIEUO7xdBU',
    appId: '1:872296974646:android:3b8fda9da90d2d8cbd0b97',
    messagingSenderId: '872296974646',
    projectId: 'siproject-c5cd0',
    storageBucket: 'siproject-c5cd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlVrqGmrVbpgER1YVpWJpO6UUhClG-URk',
    appId: '1:872296974646:ios:920d110708f72f37bd0b97',
    messagingSenderId: '872296974646',
    projectId: 'siproject-c5cd0',
    storageBucket: 'siproject-c5cd0.appspot.com',
    iosClientId: '872296974646-6e1bs4jslkhh5fhohm16tp18nd61hr26.apps.googleusercontent.com',
    iosBundleId: 'com.example.siProto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlVrqGmrVbpgER1YVpWJpO6UUhClG-URk',
    appId: '1:872296974646:ios:441f4228bb3d8329bd0b97',
    messagingSenderId: '872296974646',
    projectId: 'siproject-c5cd0',
    storageBucket: 'siproject-c5cd0.appspot.com',
    iosClientId: '872296974646-pv92k7upvtf38452b20apibj1g2boj7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.siProto.RunnerTests',
  );
}
