name: si_proto
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  pedantic_mono: any
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.0.1
  cloud_firestore: ^4.8.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.2
  get: ^4.6.5
  google_fonts: ^5.0.0
  flutter_animate: ^4.1.1+1
  gap: ^3.0.0
  intl: ^0.18.1
  settings_ui: ^2.0.2
  package_info_plus: ^4.0.2
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: lib/fonts/NotoSansJP-Black.ttf
          weight: 900
        - asset: lib/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: lib/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: lib/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: lib/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: lib/fonts/NotoSansJP-Thin.ttf
          weight: 100

  uses-material-design: true